In [60]:
import pandas as pd
import os
def processMain(EXP, N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("mainA2_1_WarmStartN"+str(N)+"_")]
    print(prefixed)
    # dfs_list = [pd.read_csv(file, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None) for file in prefixed]
    # print(dfs_list[0])
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None)
        df['Ins'] = split
        dfs_list.append(df)
        # print(df)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    # print(output)
    # for i in range(5):
    #     output = pd.read_csv(EXP+"_N"+str(N)+"_"+str(i+1)+".txt", sep=";", header=None)
        
    return output
    
def processLazy(EXP, N):
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("lazyDelay_N"+str(N)+"_")]
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['num_cases','total_time','b','ObjVal','z','x_sol'], header=None)
        df['Ins'] = split
        dfs_list.append(df)
        # print(prefixed)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    return output

EXP = 'main'
N =30
df_main = processMain(EXP, N)
df_main
# df_lazy = processLazy(EXP, N)
# df_lazy

# df_lazy.total_time.mean()

# print(df_main.total_time.sum()+3600)/10
# df_main
# (df_main.total_time.sum()+3600*2)/10
# (df_lazy.total_time.sum()+3600)/10
# df_lazy
# df_main

['mainA2_1_WarmStartN30_10.txt', 'mainA2_1_WarmStartN30_9.txt', 'mainA2_1_WarmStartN30_8.txt', 'mainA2_1_WarmStartN30_6.txt', 'mainA2_1_WarmStartN30_7.txt', 'mainA2_1_WarmStartN30_5.txt', 'mainA2_1_WarmStartN30_4.txt', 'mainA2_1_WarmStartN30_1.txt', 'mainA2_1_WarmStartN30_3.txt', 'mainA2_1_WarmStartN30_2.txt']

,iiter,total_time,b,ObjVal,x_sol,Ins
0,-1,0.386965,10,688.000000,[ 0 2 3 4 25 38 52 67 98 153],10
1,-1,1.701530,10,371.187500,[ 0 3 95 127 134 146 151 155 161 163],9
2,-1,0.402880,10,330.000000,[ 0 1 2 3 4 5 39 54 75 172],8
3,-1,2871.712806,10,413.757812,[ 2 4 6 45 62 93 100 148 157 162],6
4,-1,0.398785,10,388.000000,[ 0 1 2 3 4 5 9 133 156 164],7
5,-1,12.502239,10,321.390804,[ 1 2 34 37 38 39 50 53 69 176],5
6,-1,0.848758,10,397.000000,[ 2 3 4 5 7 91 126 132 152 159],4
7,-1,0.925928,10,564.625000,[ 0 1 2 3 24 25 32 63 85 139],1
8,-1,0.385351,10,275.000000,[ 0 1 2 3 4 63 79 84 99 141],3
9,-1,14.624172,10,463.643875,[ 0 1 2 3 4 17 55 110 119 143],2

In [19]:
(df_main.total_time.sum()+3600*3)/10

1100.523024225235

In [48]:
def processSAA_AP(N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    # print(dfs_list[0])
    # output = pd.concat(dfs_list, axis=0, ignore_index=True)
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("SAA-AP_N"+str(N)+"_")]
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['num_cases','total_time','b','ObjVal','x_sol'], header=None) 
        df['Ins'] = split
        dfs_list.append(df)
        # print(prefixed)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)    
    return output
N =50
df_SAA_AP = processSAA_AP(N)
# (df_SAA_AP[df_SAA_AP.num_cases ==50000]['total_time'].sum()+3600)/10
# df_SAA_AP
df_50 = df_SAA_AP[df_SAA_AP.num_cases ==50000].reset_index()
df_50['N']=50

N =40
df_SAA_AP = processSAA_AP(N)
df_40 = df_SAA_AP[df_SAA_AP.num_cases ==50000].reset_index()
df_40['N']=40
N =30
df_SAA_AP = processSAA_AP(N)
df_30 = df_SAA_AP[df_SAA_AP.num_cases ==50000].reset_index()
df_30['N']=30
df_starting_x  = pd.concat([df_30, df_40,df_50], ignore_index=True, sort=False)
df_starting_x = df_starting_x.drop('index', axis=1)
df_starting_x.to_csv("xSol_SAA_AP.csv")
df_starting_x

,num_cases,total_time,b,ObjVal,x_sol,Ins,N
0,50000,220.558947,10,321.359003,[ 1 2 37 38 39 50 53 176 34 69],5,30
1,50000,102.057963,10,687.782320,[ 0 2 3 4 38 67 153 25 52 98],10,30
2,50000,29.517396,10,397.019224,[ 2 3 4 5 7 152 91 126 132 159],4,30
3,50000,426.687514,10,413.608610,[ 2 4 6 45 93 100 157 162 62 148],6,30
4,50000,26.972667,10,388.000000,[ 0 1 2 3 4 5 9 133 164 156],7,30
5,50000,66.588575,10,275.000000,[ 0 1 2 3 4 63 79 141 84 99],3,30
6,50000,119.026950,10,464.018228,[ 0 1 2 3 4 17 55 143 119 110],2,30
7,50000,44.055129,10,564.154512,[ 0 1 2 3 24 25 63 85 32 139],1,30
8,50000,63.369140,10,371.119253,[ 0 3 127 134 161 163 95 146 155 151],9,30
9,50000,28.928288,10,330.000000,[ 0 1 2 3 4 5 75 172 39 54],8,30
10,50000,331.754422,10,458.184346,[ 0 50 53 71 25 48 36 308 228 232],9,40
11,50000,68.992160,10,584.993603,[ 0 1 2 3 39 40 44 225 210 211],8,40
12,50000,324.682207,10,387.494823,[ 2 8 60 61 81 169 170 153 65 124],5,40
13,50000,555.202509,10,334.421429,[ 2 4 29 49 93 116 131 250 274 243],4,40
14,50000,199.335649,10,264.083107,[ 3 5 9 10 118 236 125 292 250 122],6,40
15,50000,37.730147,10,168.000000,[ 0 1 2 3 4 5 234 200 260 274],7,40
16,50000,288.819411,10,454.807203,[ 1 2 6 50 60 155 157 135 177 139],3,40
17,50000,250.628926,10,497.055389,[ 0 2 4 57 170 253 272 289 299 165],2,40
18,50000,502.921783,10,509.240842,[ 0 1 40 90 320 277 205 243 59 254],1,40
19,50000,286.908803,10,486.394946,[ 0 1 5 17 106 292 174 234 249 299],10,40
20,50000,204.734942,10,204.004634,[ 0 1 2 3 4 5 10 45 314 452],7,50
21,50000,130.152328,10,276.000532,[ 0 1 2 3 4 22 26 436 417 448],6,50
22,50000,860.558067,10,358.042443,[ 0 1 6 16 43 159 273 347 164 420],4,50
23,50000,203.971038,10,531.000000,[ 0 1 2 3 4 5 156 32 120 381],5,50
24,50000,629.465550,10,276.715260,[ 0 2 11 314 9 447 149 300 437 375],1,50
25,50000,448.546504,10,304.244191,[ 1 49 51 89 258 265 388 344 323 155],2,50
26,50000,228.593186,10,361.000000,[ 0 2 3 4 5 6 50 16 122 167],3,50
27,50000,127.326281,10,168.000000,[ 1 2 3 144 148 201 137 232 105 119],8,50
28,50000,911.062394,10,353.517018,[ 1 4 77 128 244 283 352 427 270 472],9,50
29,50000,1075.168304,10,337.782020,[ 39 59 63 66 68 73 512 387 350 102],10,50

In [23]:
def processSeq(N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    # print(dfs_list[0])
    # output = pd.concat(dfs_list, axis=0, ignore_index=True)
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("SeqSampling_N"+str(N)+"_")]
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['num_cases','total_time','b','ObjVal','x_sol','para','opt_gap','CI_right'], header=None) 
        df['Ins'] = split
        dfs_list.append(df)
        # print(prefixed)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)    
    return output
N =50
df_Seq = processSeq(N)
# df_SAA_AP[df_SAA_AP.num_cases ==50000]['total_time'].mean()#['total_time'].sum()+3600)/10
df_Seq['total_time'].mean()
df_Seq.num_cases.mean()

49.2

In [63]:
df_SAA[(df_SAA.num_cases ==50000)&(df_SAA.b==2)]

    num_cases  total_time  b      ObjVal    x_sol
6       50000   26.058902  2   76.000000  [ 2 30]
10      50000   25.790386  2   76.000000  [ 2 30]
18      50000   76.267384  2  277.000000  [ 0 18]
22      50000   76.489195  2  277.000000  [ 0 18]
30      50000   61.703715  2  241.078650  [ 4 20]
34      50000   62.795576  2  241.078650  [ 4 20]
42      50000   45.880813  2   66.323960  [ 4 21]
46      50000   46.525756  2   66.323960  [ 4 21]
54      50000   31.046645  2  192.787031  [ 0 18]
58      50000   30.830447  2  192.787031  [ 0 18]

In [64]:
df_SeqSampling

,num_cases,total_time,b,ObjVal,x_sol,var,opt_gap,iter,para
0,49,1.594740,2,35.937095,[4 6],1.203329e+02,6.331572,23,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
1,49,1.387805,2,173.646302,[ 0 22],2.525407e-27,56.000000,20,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
2,49,0.654536,2,76.000000,[ 2 30],1.811915e-30,2.000000,7,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
3,49,0.815751,2,277.000000,[ 0 18],4.529787e-31,1.000000,9,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
4,49,18.419930,2,232.120182,[4 5],4.798603e+01,57.561440,67,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."

In [115]:
import pandas as pd
df_verify = pd.read_csv("./SolutionVerification.csv", delimiter = ";",  names=['N','Ins','alg','x_sol','numScen','b','ObjVal'], header=None)
df_verify[(df_verify.N==50)&(df_verify.Ins==10)]

,N,Ins,alg,x_sol,numScen,b,ObjVal
150,50,10,xSeq,[ 39 59 63 66 68 73 512 387 350 102],100000,10,337.719359

In [95]:
(264.094184-264.172428)#/264.172428)*100

-0.07824400000004061

In [131]:
N=50
ins = [3,5,6]
test = ['xMain', 'xLazy']
df_test = df_verify[(df_verify.N == N)&(df_verify.Ins.isin(ins))&(df_verify.alg.isin(test))]

,N,Ins,alg,x_sol,numScen,b,ObjVal
89,50,3,xMain,[ 0 1 16 42 50 72 167 190 227 299],100000,10,360.998288
90,50,3,xLazy,[ 0 2 3 4 5 6 16 50 139 167],100000,10,361.000000
98,50,5,xMain,[ 0 1 2 3 4 32 120 156 188 220],100000,10,531.000000
99,50,5,xLazy,[ 0 1 2 3 12 32 120 156 163 174],100000,10,531.000000
102,50,6,xMain,[ 0 1 2 22 26 190 228 267 417 436],100000,10,275.732289
103,50,6,xLazy,[ 0 1 2 3 4 22 26 417 436 448],100000,10,276.016264

In [133]:
((361.000000-360.998288)/360.998288+(276.016264-275.732289)/275.732289)

0.02856869999999958

In [156]:
def processMainA1(EXP, N):
    # 1A : Select an arc in $S^k$, breaking ties arbitrarily. 
    # 1B (A1=1): Select an arc that has the maximum $M$-value, breaking ties arbitrarily. 


    # 3B: A3=0: Sensitivity Analysis
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("mainA3_0_N"+str(N)+"_")]
    print(prefixed)
    # dfs_list = [pd.read_csv(file, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None) for file in prefixed]
    # print(dfs_list[0])
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None)
        df['Ins'] = split
        dfs_list.append(df)
        # print(df)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    # print(output)
    # for i in range(5):
    #     output = pd.read_csv(EXP+"_N"+str(N)+"_"+str(i+1)+".txt", sep=";", header=None)
        
    return output

EXP = 'main'
N =50
df_main = processMainA1(EXP, N)
df_main

['mainA3_0_N50_7.txt', 'mainA3_0_N50_6.txt', 'mainA3_0_N50_5.txt', 'mainA3_0_N50_3.txt', 'mainA3_0_N50_8.txt', 'mainA3_0_N50_9.txt']

,iiter,total_time,b,ObjVal,x_sol,Ins
0,-1,0.785921,10,204.000000,[ 0 1 2 10 45 65 247 314 452 461],7
1,-1,0.775880,10,276.000000,[ 0 1 2 22 26 190 228 267 417 436],6
2,-1,0.905721,10,531.000000,[ 0 1 2 3 4 32 120 156 188 220],5
3,-1,0.867478,10,361.000000,[ 0 1 16 42 50 72 167 190 227 299],3
4,-1,1.591061,10,168.000000,[ 2 117 119 137 144 145 148 201 232 495],8
5,-1,54.496644,10,353.213327,[ 1 4 77 128 244 270 283 352 427 472],9

In [158]:
(df_main['total_time'].sum() + 3600*4)/10

1445.9422705411912

In [130]:
df_xSol = pd.read_csv("./xSol_SAA_AP.csv")
df_xSol

,Unnamed: 0,num_cases,total_time,b,ObjVal,x_sol,Ins,N
0,0,50000,220.558947,10,321.359003,[ 1 2 37 38 39 50 53 176 34 69],5,30
1,1,50000,102.057963,10,687.782320,[ 0 2 3 4 38 67 153 25 52 98],10,30
2,2,50000,29.517396,10,397.019224,[ 2 3 4 5 7 152 91 126 132 159],4,30
3,3,50000,426.687514,10,413.608610,[ 2 4 6 45 93 100 157 162 62 148],6,30
4,4,50000,26.972667,10,388.000000,[ 0 1 2 3 4 5 9 133 164 156],7,30
5,5,50000,66.588575,10,275.000000,[ 0 1 2 3 4 63 79 141 84 99],3,30
6,6,50000,119.026950,10,464.018228,[ 0 1 2 3 4 17 55 143 119 110],2,30
7,7,50000,44.055129,10,564.154512,[ 0 1 2 3 24 25 63 85 32 139],1,30
8,8,50000,63.369140,10,371.119253,[ 0 3 127 134 161 163 95 146 155 151],9,30
9,9,50000,28.928288,10,330.000000,[ 0 1 2 3 4 5 75 172 39 54],8,30
10,10,50000,331.754422,10,458.184346,[ 0 50 53 71 25 48 36 308 228 232],9,40
11,11,50000,68.992160,10,584.993603,[ 0 1 2 3 39 40 44 225 210 211],8,40
12,12,50000,324.682207,10,387.494823,[ 2 8 60 61 81 169 170 153 65 124],5,40
13,13,50000,555.202509,10,334.421429,[ 2 4 29 49 93 116 131 250 274 243],4,40
14,14,50000,199.335649,10,264.083107,[ 3 5 9 10 118 236 125 292 250 122],6,40
15,15,50000,37.730147,10,168.000000,[ 0 1 2 3 4 5 234 200 260 274],7,40
16,16,50000,288.819411,10,454.807203,[ 1 2 6 50 60 155 157 135 177 139],3,40
17,17,50000,250.628926,10,497.055389,[ 0 2 4 57 170 253 272 289 299 165],2,40
18,18,50000,502.921783,10,509.240842,[ 0 1 40 90 320 277 205 243 59 254],1,40
19,19,50000,286.908803,10,486.394946,[ 0 1 5 17 106 292 174 234 249 299],10,40
20,20,50000,204.734942,10,204.004634,[ 0 1 2 3 4 5 10 45 314 452],7,50
21,21,50000,130.152328,10,276.000532,[ 0 1 2 3 4 22 26 436 417 448],6,50
22,22,50000,860.558067,10,358.042443,[ 0 1 6 16 43 159 273 347 164 420],4,50
23,23,50000,203.971038,10,531.000000,[ 0 1 2 3 4 5 156 32 120 381],5,50
24,24,50000,629.465550,10,276.715260,[ 0 2 11 314 9 447 149 300 437 375],1,50
25,25,50000,448.546504,10,304.244191,[ 1 49 51 89 258 265 388 344 323 155],2,50
26,26,50000,228.593186,10,361.000000,[ 0 2 3 4 5 6 50 16 122 167],3,50
27,27,50000,127.326281,10,168.000000,[ 1 2 3 144 148 201 137 232 105 119],8,50
28,28,50000,911.062394,10,353.517018,[ 1 4 77 128 244 283 352 427 270 472],9,50
29,29,50000,1075.168304,10,337.782020,[ 39 59 63 66 68 73 512 387 350 102],10,50

In [117]:
import numpy as np
myX = df_xSol.loc[(df_xSol.N == 30)&(df_xSol.Ins == 1), 'x_sol'].values[0]
print(type(myX))

<class 'str'>

In [119]:
xvals = [] #model.cbGetSolution(model._x)
string_array_cleaned = myX.strip("[]")  # Remove brackets
string_list = string_array_cleaned.split()
x_int = np.array(list(map(int, string_list)))
for a in x_int:
    # print(a)
    xvals.append((edge[a][0], edge[a][1]))
print(xvals)

NameError: name 'edge' is not defined

In [27]:
import numpy as np

cL = [2,3,4]
cU = [2,5,6]

np.random.uniform(cL, cU)

np.std(cL)

0.816496580927726

In [36]:
from scipy import stats
alpha = 0.01
n_sided = 2
z_crit = stats.norm.ppf(1-alpha/n_sided)
z_crit

2.5758293035489004

In [41]:
#Studnt, n=999, p<0.05, 2-tail
#equivalent to Excel TINV(0.05,999)
print(stats.t.ppf(1-0.025, 999))

1.9623414611334487

In [47]:
n=50
s=10
t_score = stats.t.ppf(1-0.01/2, n)
optimality_gap = t_score*(s/np.sqrt(n))*2
optimality_gap

7.573943121991902

In [57]:
int(np.ceil(optimality_gap))

8