In [188]:
import pandas as pd
import os
def processMain(EXP, N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("main_N"+str(N)+"_")]
    print(prefixed)
    # dfs_list = [pd.read_csv(file, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None) for file in prefixed]
    # print(dfs_list[0])
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None)
        df['Ins'] = split
        dfs_list.append(df)
        # print(df)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    # print(output)
    # for i in range(5):
    #     output = pd.read_csv(EXP+"_N"+str(N)+"_"+str(i+1)+".txt", sep=";", header=None)
        
    return output
    
def processLazy(EXP, N):
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("lazyDelay_N"+str(N)+"_")]
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['num_cases','total_time','b','ObjVal','z','x_sol'], header=None)
        df['Ins'] = split
        dfs_list.append(df)
        # print(prefixed)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    return output

EXP = 'main'
N =30
df_main = processMain(EXP, N)
df_main
df_lazy = processLazy(EXP, N)
df_lazy

df_lazy.total_time.mean()

# print(df_main.total_time.sum()+3600)/10
df_main
# (df_main.total_time.sum()+3600*2)/10
# (df_lazy.total_time.sum()+3600)/10
# df_lazy
# df_main

['main_N30_4.txt', 'main_N30_5.txt', 'main_N30_7.txt', 'main_N30_2.txt', 'main_N30_3.txt', 'main_N30_1.txt', 'main_N30_10.txt', 'main_N30_8.txt', 'main_N30_9.txt']

,iiter,total_time,b,ObjVal,x_sol,Ins
0,-1,1.219656,10,397.000000,[ 0 1 4 7 26 91 126 132 152 159],4
1,-1,14.366338,10,321.390804,[ 1 2 34 37 38 39 50 53 69 176],5
2,-1,0.377611,10,388.000000,[ 0 1 2 3 4 5 6 9 133 164],7
3,-1,39.781799,10,463.643875,[ 0 1 2 15 17 55 59 101 110 119],2
4,-1,1.750650,10,275.000000,[ 0 1 2 3 4 76 79 84 91 141],3
5,-1,2.249137,10,564.164062,[ 0 1 2 3 4 5 6 32 63 85],1
6,-1,1.211894,10,688.000000,[ 0 1 2 25 38 52 67 70 98 153],10
7,-1,0.410036,10,330.000000,[ 0 1 2 3 4 5 6 39 75 172],8
8,-1,11.285004,10,371.078102,[ 0 1 2 3 127 134 146 155 161 163],9

In [408]:
def processSAA_AP(N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    # print(dfs_list[0])
    # output = pd.concat(dfs_list, axis=0, ignore_index=True)
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("SAA_N"+str(N)+"_")]
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['num_cases','total_time','b','ObjVal','x_sol'], header=None) 
        df['Ins'] = split
        dfs_list.append(df)
        # print(prefixed)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)    
    return output
N =50
df_SAA_AP = processSAA_AP(N)
(df_SAA_AP[df_SAA_AP.num_cases ==50000]['total_time'].sum()+3600)/10
# df_SAA_AP

748.4097908496857

In [396]:
def processSeq(N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    # print(dfs_list[0])
    # output = pd.concat(dfs_list, axis=0, ignore_index=True)
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("SeqSampling_N"+str(N)+"_")]
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['num_cases','total_time','b','ObjVal','x_sol','para','opt_gap','CI_right'], header=None) 
        df['Ins'] = split
        dfs_list.append(df)
        # print(prefixed)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)    
    return output
N =50
df_Seq = processSeq(N)
# df_SAA_AP[df_SAA_AP.num_cases ==50000]['total_time'].mean()#['total_time'].sum()+3600)/10
df_Seq['total_time'].mean()
df_Seq

,num_cases,total_time,b,ObjVal,x_sol,para,opt_gap,CI_right,Ins
0,49,1.341453,10,279.358935,[ 0 2 11 314 9 447 149 300 437 375],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],1
1,49,0.874771,10,361.000000,[ 0 1 2 3 50 227 167 139 190 293],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],3
2,49,1.902209,10,300.646567,[ 1 49 51 89 107 258 265 344 323 155],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],2
3,49,1.055044,10,276.245981,[ 0 1 2 3 4 22 26 436 417 448],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],6
4,49,0.779226,10,203.601439,[ 0 1 2 3 4 10 45 314 452 290],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],7
5,50,4.387034,10,334.339483,[ 39 59 63 66 68 73 512 387 350 102],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],10
6,50,1.579884,10,531.000000,[ 0 1 2 3 4 5 6 156 32 381],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],5
7,49,3.016761,10,359.755476,[ 0 6 16 28 159 273 311 347 164 420],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],4
8,49,2.305824,10,354.918752,[ 1 4 77 128 244 283 352 427 270 472],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],9
9,49,1.151994,10,168.000000,[ 1 2 3 144 148 201 137 232 117 119],"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000...",0.0,[0 2e-07],8

In [63]:
df_SAA[(df_SAA.num_cases ==50000)&(df_SAA.b==2)]

    num_cases  total_time  b      ObjVal    x_sol
6       50000   26.058902  2   76.000000  [ 2 30]
10      50000   25.790386  2   76.000000  [ 2 30]
18      50000   76.267384  2  277.000000  [ 0 18]
22      50000   76.489195  2  277.000000  [ 0 18]
30      50000   61.703715  2  241.078650  [ 4 20]
34      50000   62.795576  2  241.078650  [ 4 20]
42      50000   45.880813  2   66.323960  [ 4 21]
46      50000   46.525756  2   66.323960  [ 4 21]
54      50000   31.046645  2  192.787031  [ 0 18]
58      50000   30.830447  2  192.787031  [ 0 18]

In [64]:
df_SeqSampling

,num_cases,total_time,b,ObjVal,x_sol,var,opt_gap,iter,para
0,49,1.594740,2,35.937095,[4 6],1.203329e+02,6.331572,23,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
1,49,1.387805,2,173.646302,[ 0 22],2.525407e-27,56.000000,20,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
2,49,0.654536,2,76.000000,[ 2 30],1.811915e-30,2.000000,7,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
3,49,0.815751,2,277.000000,[ 0 18],4.529787e-31,1.000000,9,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
4,49,18.419930,2,232.120182,[4 5],4.798603e+01,57.561440,67,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."

In [210]:
df_verify = pd.read_csv("./SolutionVerification.csv", delimiter = ";",  names=['N','Ins','alg','x_sol','numScen','b','ObjVal'], header=None)
df_verify

,N,Ins,alg,x_sol,numScen,b,ObjVal
0,30,1,xMain,[ 0 1 2 3 4 5 6 32 63 85],100000,10,564.134787
1,30,1,xLazy,[ 0 1 2 32 39 52 63 85 105 178],100000,10,564.134787
2,30,1,xSAA,[ 0 1 2 3 24 25 63 85 32 139],100000,10,564.134787
3,30,1,xSAA_AP,[ 1 2 3 24 25 26 63 85 32 139],100000,10,564.134787
4,30,1,xSeq,[ 0 1 2 3 24 25 63 85 32 139],100000,10,564.134787
...,...,...,...,...,...,...,...
116,50,9,xMain,[ 1 4 77 128 244 270 283 352 427 472],100000,10,353.478107
117,50,9,xLazy,[ 1 4 77 128 244 270 283 352 427 472],100000,10,353.478107
118,50,9,xSAA,[ 1 4 77 128 244 283 352 427 270 472],100000,10,353.478107
119,50,9,xSAA_AP,[ 1 4 77 128 244 283 352 427 270 472],100000,10,353.478107
120,50,9,xSeq,[ 1 4 77 128 244 283 352 427 270 472],100000,10,353.478107

In [315]:
N=50
ins=10
df_verify[(df_verify.N == N)&(df_verify.Ins == ins)]

Empty DataFrame
Columns: [N, Ins, alg, x_sol, numScen, b, ObjVal]
Index: []

In [ ]:
df_group